global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 10.0    # Useful when working with dynamic maps
   publish_frequency: 10.0
   static_map: $(arg unknown_map_negado)
   rolling_window: false # Follow robot while navigating
   transform_tolerance: 0.5
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}